num1 = float(input("digite o primeiro valor "))
num2 = float(input("digite o segundo valor "))
num3 = float(input("digite o terceiro valor "))
tot = ((num1 + num2 + num3) / 3)
print("a média aritmética é" ,tot)